# Generated by Django 2.0.5 on 2018-06-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyser', '0003_wordborder'),
        ('lyser', '0003_user_prof'),
    ]

    operations = [
    ]
