# Generated by Django 2.0.5 on 2018-06-18 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyser', '0004_merge_20180617_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_prof',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
